### PR TITLE
Fix error in ACP.

### PR DESCRIPTION
**Pull request by Dark1z**
Err0r : `[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/db/driver/mysqli.php on line 317: mysqli_free_result() expects parameter 1 to be mysqli_result, array given`

Best regards 👍

### CODE REVIEW

**Comment by Dark1z** [comment]
@CleanTalk Team,

BTW , why do not you add Travis CI ???

Best regards 👍

**Comment by Dark1z** [comment]
@davydovct ,
Any thoughts on this :  

> BTW , why do not you add Travis CI ???
  
I can help with that...

Best regards 👍

**Comment by shagimuratov** [comment]
@dark-1, sure it will be great.

I am going to delegate you contributor rights. Is it enough?

**Comment by Dark1z** [comment]
@shagimuratov ,

Yea! You mean collaborator?
But first the account @CleanTalk need to make account at travis-ci.com via GitHub Oauth.

Then as collaborator I can do required settings in Travis site & on this repo.

Best regards 👍

**Comment by shagimuratov** [comment]
Ok, please let me some time, I will write you back as finish.

**Comment by CleanTalk** [comment]
Here you are. Please try to apply the settings.

**Comment by Dark1z** [comment]
Ok.
Thanks I'll start working... 👍 

Best regards 👍

**Comment by dark-1** [comment]
@shagimuratov , few steps to be done via @CleanTalk .
1. Sign up with Travis CI at travis-ci.com via @CleanTalk GitHub account.
2. Give the required access to TravisCI.

Best regards 👍

**Comment by Dark1z** [comment]
@shagimuratov , 

https://github.com/CleanTalk/phpbb3.1-3.2-antispam/commit/c59adcf07f4a3a6278b236a0e433badbce5ed6b7
In branch **dev** i have added the `.travis.yml` config file.

Done 👍

**Comment by CleanTalk** [comment]
Thanks. I have merged it,
https://github.com/CleanTalk/phpbb3.1-3.2-antispam

**Comment by Dark1z** [comment]
Nice. :smiley:

**Pull request merged**
